# Generated by Django 5.0.3 on 2024-07-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(db_index=True, default='url-title', max_length=300, verbose_name='نام در url'),
            preserve_default=False,
        ),
    ]
