# Generated by Django 5.0.3 on 2024-07-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemodule', '0005_alter_slider_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.URLField(verbose_name='لینک'),
        ),
    ]
