# Generated by Django 5.0.3 on 2024-07-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemodule', '0006_alter_slider_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='url_title',
            field=models.CharField(max_length=200, verbose_name='عنوان لینک'),
        ),
    ]
