# Generated by Django 5.0.3 on 2024-07-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemodule', '0010_sitebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='position',
            field=models.CharField(choices=[('product_list', 'صفحه لیست محصولات'), ('product_detail', 'صفحه ی جزییات محصولات'), ('about_us', 'درباره ما')], max_length=200, verbose_name='جایگاه نمایشی'),
        ),
    ]
